<a href="https://colab.research.google.com/github/MethEthPro/colab/blob/main/mlp/WEEK_1_introduction_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pandas

**Learning Objectives:**

* Gain an introduction to the `DataFrame` and `Series` data structures of the *pandas* library
* Access and manipulate data within a `DataFrame` and `Series`

[*pandas*](http://pandas.pydata.org/) is a column-oriented data analysis API.
It's a great tool for handling and analyzing input data, and many ML frameworks
support *pandas* data structures as inputs.  

Although a comprehensive
introduction to the API would span many pages, the core concepts are fairly
straightforward, and we'll present them below. For a more complete reference,
the [*pandas* docs site](http://pandas.pydata.org/pandas-docs/stable/index.html)
contains extensive documentation and many tutorials. (Note that Colab may use a
slightly older version number, but the parts of *pandas* covered here are
unlikely to differ from version to version.)

Let's import ```pandas``` library

In [168]:
import pandas as pd
pd.__version__

'2.2.2'

The primary data structures in *pandas* are implemented as two classes:

  * **`DataFrame`**, which you can imagine as a relational data table, with rows and named columns.
  * **`Series`**, which is a single column. Each row can be labeled via an index. A DataFrame contains one or more Series and a name for each Series.

The data frame is a commonly used abstraction for data manipulation. Similar implementations exist in Spark and R.

In [169]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes(as_frame=True)
print(type(diabetes['data']))

<class 'pandas.core.frame.DataFrame'>

In [170]:
?load_diabetes

In [171]:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [172]:
df = diabetes['data']

In [173]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

## Creating pandas dataframe from series

In [174]:
cities = pd.Series(['Mumbai', 'Bangalore', 'Chennai', 'Delhi'])
population = pd.Series([17000000, 13000000, 6000000])

In [175]:
city_info_df = pd.DataFrame({'City': cities, 'Population': population})

In [176]:
type(city_info_df)

pandas.core.frame.DataFrame

In [177]:
city_info_df

        City  Population
0     Mumbai  17000000.0
1  Bangalore  13000000.0
2    Chennai   6000000.0
3      Delhi         NaN

# Exploring data in dataframe

In [178]:
df2 = pd.read_csv("V5.csv")
df2

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

Find out the number of rows and columns in the dataframe.

In [179]:
df.shape

(442, 10)

In [180]:
df2.shape

(10000, 12)

In this case, there are 442 rows and 10 columns.

Let's see the names of the columns

In [181]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [182]:
df2.columns

Index(['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property',
       'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area',
       'property_tax_rate', 'Face'],
      dtype='object')

In [183]:
list(df.columns)

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [184]:
list(df2.columns)

['Date',
 'Year',
 'Locality',
 'Estimated Value',
 'Sale Price',
 'Property',
 'Residential',
 'num_rooms',
 'num_bathrooms',
 'carpet_area',
 'property_tax_rate',
 'Face']

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [186]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  object
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   object
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  object
 6   Residential        10000 non-null  object
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  object
dtypes: float64(4), int64(3), object(5)
memory usage: 937.6+ KB

Quickly examine a few entries in the dataframe.  Say first 5 and last 5.

In [187]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [188]:
df.tail()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [189]:
df2.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [190]:
df2.tail()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

Let's get summary statistics on the dataframe

In [191]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [192]:
df2.describe()

,Year,Estimated Value,Sale Price,num_rooms,num_bathrooms,carpet_area,property_tax_rate
count,10000.000000,8.757000e+03,1.000000e+04,10000.000000,10000.000000,8771.000000,10000.000000
mean,2015.904900,4.377749e+05,6.129367e+05,3.335000,2.326400,1115.160871,1.148257
std,4.045725,7.799885e+05,1.102810e+06,0.886258,1.207977,308.026850,0.168458
min,2009.000000,9.800000e+02,2.000000e+03,3.000000,1.000000,900.000000,1.003979
25%,2012.000000,1.280300e+05,1.560000e+05,3.000000,1.000000,960.000000,1.023495
50%,2016.000000,2.300200e+05,3.250000e+05,3.000000,2.000000,1021.000000,1.025899
75%,2019.000000,4.253200e+05,6.150000e+05,3.000000,3.000000,1083.000000,1.348259
max,2022.000000,2.111991e+07,2.575000e+07,8.000000,8.000000,2989.000000,1.422308

In [193]:
df.describe(percentiles=[0.2, 0.6, 0.8])

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
20%,-4.547248e-02,-4.464164e-02,-4.048038e-02,-4.009893e-02,-3.871969e-02,-3.695017e-02,-3.971921e-02,-3.949338e-02,-4.117617e-02,-3.835666e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
60%,1.628068e-02,5.068012e-02,5.218854e-03,8.100982e-03,8.062710e-03,8.706873e-03,8.142084e-03,-2.592262e-03,1.255119e-02,7.206516e-03
80%,4.170844e-02,5.068012e-02,4.229559e-02,4.941519e-02,3.943444e-02,3.952068e-02,3.759519e-02,3.430886e-02,3.885335e-02,3.620126e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [194]:
df2.describe(percentiles=[0.2,0.4,0.6,0.8])

,Year,Estimated Value,Sale Price,num_rooms,num_bathrooms,carpet_area,property_tax_rate
count,10000.000000,8.757000e+03,1.000000e+04,10000.000000,10000.000000,8771.000000,10000.000000
mean,2015.904900,4.377749e+05,6.129367e+05,3.335000,2.326400,1115.160871,1.148257
std,4.045725,7.799885e+05,1.102810e+06,0.886258,1.207977,308.026850,0.168458
min,2009.000000,9.800000e+02,2.000000e+03,3.000000,1.000000,900.000000,1.003979
20%,2012.000000,1.146080e+05,1.330000e+05,3.000000,1.000000,947.000000,1.021958
40%,2015.000000,1.799700e+05,2.500000e+05,3.000000,2.000000,996.000000,1.025440
50%,2016.000000,2.300200e+05,3.250000e+05,3.000000,2.000000,1021.000000,1.025899
60%,2017.000000,2.911780e+05,4.150000e+05,3.000000,3.000000,1045.000000,1.025953
80%,2020.000000,5.088920e+05,7.250000e+05,3.000000,3.000000,1094.000000,1.350819
max,2022.000000,2.111991e+07,2.575000e+07,8.000000,8.000000,2989.000000,1.422308

In [195]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,442.0,-2.511817e-19,0.047619,-0.107226,-0.037299,0.005383,0.038076,0.110727
sex,442.0,1.230790e-17,0.047619,-0.044642,-0.044642,-0.044642,0.050680,0.050680
bmi,442.0,-2.245564e-16,0.047619,-0.090275,-0.034229,-0.007284,0.031248,0.170555
bp,442.0,-4.797570e-17,0.047619,-0.112399,-0.036656,-0.005670,0.035644,0.132044
s1,442.0,-1.381499e-17,0.047619,-0.126781,-0.034248,-0.004321,0.028358,0.153914
s2,442.0,3.918434e-17,0.047619,-0.115613,-0.030358,-0.003819,0.029844,0.198788
s3,442.0,-5.777179e-18,0.047619,-0.102307,-0.035117,-0.006584,0.029312,0.181179
s4,442.0,-9.042540e-18,0.047619,-0.076395,-0.039493,-0.002592,0.034309,0.185234
s5,442.0,9.293722e-17,0.047619,-0.126097,-0.033246,-0.001947,0.032432,0.133597
s6,442.0,1.130318e-17,0.047619,-0.137767,-0.033179,-0.001078,0.027917,0.135612

In [196]:
df2.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,10000.0,2015.904900,4.045725e+00,2009.000000,2012.000000,2016.000000,2019.000000,2.022000e+03
Estimated Value,8757.0,437774.885806,7.799885e+05,980.000000,128030.000000,230020.000000,425320.000000,2.111991e+07
Sale Price,10000.0,612936.652090,1.102810e+06,2000.000000,156000.000000,325000.000000,615000.000000,2.575000e+07
num_rooms,10000.0,3.335000,8.862582e-01,3.000000,3.000000,3.000000,3.000000,8.000000e+00
num_bathrooms,10000.0,2.326400,1.207977e+00,1.000000,1.000000,2.000000,3.000000,8.000000e+00
carpet_area,8771.0,1115.160871,3.080269e+02,900.000000,960.000000,1021.000000,1083.000000,2.989000e+03
property_tax_rate,10000.0,1.148257,1.684579e-01,1.003979,1.023495,1.025899,1.348259,1.422308e+00

## Selection

In [197]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [198]:
df2.columns

Index(['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property',
       'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area',
       'property_tax_rate', 'Face'],
      dtype='object')

In [199]:
df['age']

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...
437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, Length: 442, dtype: float64

In [200]:
df2['Year']

0       2009
1       2009
2       2009
3       2009
4       2009
        ...
9995    2022
9996    2022
9997    2022
9998    2022
9999    2022
Name: Year, Length: 10000, dtype: int64

In [201]:
type(df['age'])

pandas.core.series.Series

In [202]:
type(df2['Year'])

pandas.core.series.Series

In [203]:
df['age'][0]

0.038075906433423026

In [204]:
df2['Year'][0]

2009

In [205]:
df['age'][:5]

0    0.038076
1   -0.001882
2    0.085299
3   -0.089063
4    0.005383
Name: age, dtype: float64

In [206]:
df2["Year"][:5]

0    2009
1    2009
2    2009
3    2009
4    2009
Name: Year, dtype: int64

In [207]:
df['age'][-5:]

437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, dtype: float64

In [208]:
df2['Year'][:-5]

0       2009
1       2009
2       2009
3       2009
4       2009
        ...
9990    2022
9991    2022
9992    2022
9993    2022
9994    2022
Name: Year, Length: 9995, dtype: int64

In [209]:
df['age'][100:200]

100    0.016281
101    0.016281
102   -0.092695
103    0.059871
104   -0.027310
         ...
195    0.027178
196   -0.023677
197    0.048974
198   -0.052738
199    0.041708
Name: age, Length: 100, dtype: float64

In [210]:
df2["Year"][100:130]

100    2009
101    2009
102    2009
103    2009
104    2009
105    2009
106    2009
107    2009
108    2009
109    2009
110    2009
111    2009
112    2009
113    2009
114    2009
115    2009
116    2009
117    2009
118    2009
119    2009
120    2009
121    2009
122    2009
123    2009
124    2009
125    2009
126    2009
127    2009
128    2009
129    2009
Name: Year, dtype: int64

In [211]:
df[['age', 'sex']]

          age       sex
0    0.038076  0.050680
1   -0.001882 -0.044642
2    0.085299  0.050680
3   -0.089063 -0.044642
4    0.005383 -0.044642
..        ...       ...
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

[442 rows x 2 columns]

In [212]:
df2.columns

Index(['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property',
       'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area',
       'property_tax_rate', 'Face'],
      dtype='object')

In [213]:
df2[['Date','Year']]

            Date  Year
0     2009-01-02  2009
1     2009-01-02  2009
2     2009-01-02  2009
3     2009-01-02  2009
4     2009-01-02  2009
...          ...   ...
9995  2022-09-30  2022
9996  2022-09-30  2022
9997  2022-09-30  2022
9998  2022-09-30  2022
9999  2022-09-30  2022

[10000 rows x 2 columns]

In [214]:
df[['age', 'sex']][:5]

        age       sex
0  0.038076  0.050680
1 -0.001882 -0.044642
2  0.085299  0.050680
3 -0.089063 -0.044642
4  0.005383 -0.044642

In [215]:
df[['age', 'sex']][-5:]

          age       sex
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

In [216]:
df[['age', 'sex']]

          age       sex
0    0.038076  0.050680
1   -0.001882 -0.044642
2    0.085299  0.050680
3   -0.089063 -0.044642
4    0.005383 -0.044642
..        ...       ...
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

[442 rows x 2 columns]

* ```.loc```
* ```.iloc```

In [217]:
df.iloc[441]

age   -0.045472
sex   -0.044642
bmi   -0.073030
bp    -0.081413
s1     0.083740
s2     0.027809
s3     0.173816
s4    -0.039493
s5    -0.004222
s6     0.003064
Name: 441, dtype: float64

In [218]:
df2.iloc[400]

Date                   2009-06-25
Year                         2009
Locality                Waterbury
Estimated Value           35420.0
Sale Price               154000.0
Property             Three Family
Residential               Triplex
num_rooms                       6
num_bathrooms                   6
carpet_area                2109.0
property_tax_rate        1.025953
Face                        North
Name: 400, dtype: object

In [219]:
df.iloc[0]

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [220]:
df2.iloc[400]

Date                   2009-06-25
Year                         2009
Locality                Waterbury
Estimated Value           35420.0
Sale Price               154000.0
Property             Three Family
Residential               Triplex
num_rooms                       6
num_bathrooms                   6
carpet_area                2109.0
property_tax_rate        1.025953
Face                        North
Name: 400, dtype: object

In [221]:
df2.loc[400]

Date                   2009-06-25
Year                         2009
Locality                Waterbury
Estimated Value           35420.0
Sale Price               154000.0
Property             Three Family
Residential               Triplex
num_rooms                       6
num_bathrooms                   6
carpet_area                2109.0
property_tax_rate        1.025953
Face                        North
Name: 400, dtype: object

In [222]:
df.loc[0]

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [223]:
df.head(n=5)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [224]:
df2.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [225]:
df2.loc[0]

Date                     2009-01-02
Year                           2009
Locality                  Waterbury
Estimated Value            111440.0
Sale Price                 185000.0
Property              Single Family
Residential          Detached House
num_rooms                         3
num_bathrooms                     3
carpet_area                   996.0
property_tax_rate          1.025953
Face                          South
Name: 0, dtype: object

In [226]:
df2.loc[0,['Year','Date']]

Year          2009
Date    2009-01-02
Name: 0, dtype: object

In [227]:
df2.iloc[0,[1,0]]

Year          2009
Date    2009-01-02
Name: 0, dtype: object

In [228]:
df.loc[4, 'age']

0.005383060374248237

In [229]:
df.loc[4, ['age', 'sex']]

age    0.005383
sex   -0.044642
Name: 4, dtype: float64

In [230]:
df.iloc[4, [1, 5, 7, 9]]

sex   -0.044642
s2     0.015596
s4    -0.002592
s6    -0.046641
Name: 4, dtype: float64

In [231]:
rows_condition_met = df.age > 5.383060e-03

In [232]:
df.loc[rows_condition_met]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349
...,...,...,...,...,...,...,...,...,...,...
431,0.070769,0.050680,-0.030996,0.021872,-0.037344,-0.047034,0.033914,-0.039493,-0.014960,-0.001078
432,0.009016,-0.044642,0.055229,-0.005670,0.057597,0.044719,-0.002903,0.023239,0.055686,0.106617
434,0.016281,-0.044642,0.001339,0.008101,0.005311,0.010899,0.030232,-0.039493,-0.045424,0.032059
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491

In [233]:
df.loc[df.age > 5.383060e-03]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349
...,...,...,...,...,...,...,...,...,...,...
431,0.070769,0.050680,-0.030996,0.021872,-0.037344,-0.047034,0.033914,-0.039493,-0.014960,-0.001078
432,0.009016,-0.044642,0.055229,-0.005670,0.057597,0.044719,-0.002903,0.023239,0.055686,0.106617
434,0.016281,-0.044642,0.001339,0.008101,0.005311,0.010899,0.030232,-0.039493,-0.045424,0.032059
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491

In [234]:
age_df_temp = df.loc[df.age < 5.383060e-03]

In [235]:
age_df_temp.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504

In [236]:
age_df_temp.iloc[2]

age   -0.092695
sex   -0.044642
bmi   -0.040696
bp    -0.019442
s1    -0.068991
s2    -0.079288
s3     0.041277
s4    -0.076395
s5    -0.041176
s6    -0.096346
Name: 5, dtype: float64

In [237]:
age_df_temp.loc[1]

age   -0.001882
sex   -0.044642
bmi   -0.051474
bp    -0.026328
s1    -0.008449
s2    -0.019163
s3     0.074412
s4    -0.039493
s5    -0.068332
s6    -0.092204
Name: 1, dtype: float64

In [238]:
age_df_temp = df.loc[(df.age < 5.383060e-03) & (df.sex > -4.464164e-02 )]

In [239]:
age_df_temp.shape

(214, 10)

In [240]:
age_df_temp

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504
...,...,...,...,...,...,...,...,...,...,...
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
436,-0.056370,-0.044642,-0.074108,-0.050427,-0.024960,-0.047034,0.092820,-0.076395,-0.061176,-0.046641
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [241]:
df2.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [242]:
df2_high_sp_south = df2.loc[(df2['Sale Price'] > 200000) & (df2["Face"]=="South")]
df2_high_sp_south

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
6,2009-01-02,2009,Norwalk,571060.0,1000000.0,Single Family,Detached House,3,2,NaN,1.025953,South
10,2009-01-03,2009,Bridgeport,122150.0,256500.0,Single Family,Detached House,3,1,926.0,1.025953,South
13,2009-01-03,2009,Greenwich,1046920.0,600000.0,Single Family,Detached House,3,3,1068.0,1.025953,South
14,2009-01-04,2009,Bridgeport,NaN,300000.0,Three Family,Triplex,6,4,2174.0,1.025953,South
15,2009-01-04,2009,Norwalk,208880.0,370000.0,Single Family,Detached House,3,2,1063.0,1.025953,South
...,...,...,...,...,...,...,...,...,...,...,...,...
9980,2022-09-25,2022,Bridgeport,102270.0,283000.0,?,Detached House,3,1,NaN,1.003979,South
9984,2022-09-28,2022,Stamford,475140.0,730000.0,?,Detached House,3,1,977.0,1.003979,South
9988,2022-09-29,2022,Stamford,NaN,454000.0,Single Family,Detached House,3,3,936.0,1.003979,South
9989,2022-09-29,2022,Stamford,373530.0,485000.0,?,Detached House,3,3,1084.0,1.003979,South
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South

In [243]:
list("ABCD")

['A', 'B', 'C', 'D']

In [244]:
list("abcdefghi")

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

In [245]:
range(100)

range(0, 100)

In [246]:
import numpy as np

In [247]:
another_df = pd.DataFrame(
    np.random.rand(100, 4),
    index=range(10, 110),
    columns=list("ABCD"))

In [248]:
another_df

            A         B         C         D
10   0.897560  0.445992  0.685267  0.530267
11   0.860469  0.630708  0.711198  0.136328
12   0.533272  0.729880  0.714261  0.920421
13   0.399659  0.804779  0.410593  0.381301
14   0.092290  0.294069  0.268970  0.347960
..        ...       ...       ...       ...
105  0.391419  0.391457  0.905095  0.894925
106  0.605903  0.200882  0.941226  0.440815
107  0.718441  0.731170  0.055541  0.730556
108  0.161517  0.899260  0.699755  0.444812
109  0.422504  0.450539  0.656441  0.575817

[100 rows x 4 columns]

In [249]:
another_df.tail()

            A         B         C         D
105  0.391419  0.391457  0.905095  0.894925
106  0.605903  0.200882  0.941226  0.440815
107  0.718441  0.731170  0.055541  0.730556
108  0.161517  0.899260  0.699755  0.444812
109  0.422504  0.450539  0.656441  0.575817

In [250]:
df = pd.DataFrame(np.random.rand(9, 4), index=list("abcdefghi"), columns=list("ABCD"))

In [251]:
df.shape

(9, 4)

In [252]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [253]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, a to i
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      float64
 1   B       9 non-null      float64
 2   C       9 non-null      float64
 3   D       9 non-null      float64
dtypes: float64(4)
memory usage: 360.0+ bytes

In [254]:
df.head()

          A         B         C         D
a  0.700538  0.832793  0.744989  0.911335
b  0.172791  0.475595  0.879697  0.961754
c  0.923574  0.978588  0.064432  0.623384
d  0.265097  0.735282  0.132408  0.262589
e  0.181844  0.637385  0.549071  0.444988

In [255]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')

In [256]:
df.loc['a']

A    0.700538
B    0.832793
C    0.744989
D    0.911335
Name: a, dtype: float64

In [257]:
df.loc['a', 'A':'D']

A    0.700538
B    0.832793
C    0.744989
D    0.911335
Name: a, dtype: float64

In [258]:
df.loc['a':'d', :]

          A         B         C         D
a  0.700538  0.832793  0.744989  0.911335
b  0.172791  0.475595  0.879697  0.961754
c  0.923574  0.978588  0.064432  0.623384
d  0.265097  0.735282  0.132408  0.262589

In [259]:
df.iloc[:4, 0:3]

          A         B         C
a  0.700538  0.832793  0.744989
b  0.172791  0.475595  0.879697
c  0.923574  0.978588  0.064432
d  0.265097  0.735282  0.132408

In [260]:
df.iloc[:4, 1:3]

          B         C
a  0.832793  0.744989
b  0.475595  0.879697
c  0.978588  0.064432
d  0.735282  0.132408

In [261]:
df.iloc[0:4, :]

          A         B         C         D
a  0.700538  0.832793  0.744989  0.911335
b  0.172791  0.475595  0.879697  0.961754
c  0.923574  0.978588  0.064432  0.623384
d  0.265097  0.735282  0.132408  0.262589

In [262]:
df.iloc[0:4]

          A         B         C         D
a  0.700538  0.832793  0.744989  0.911335
b  0.172791  0.475595  0.879697  0.961754
c  0.923574  0.978588  0.064432  0.623384
d  0.265097  0.735282  0.132408  0.262589

In [263]:
df.iloc[:, 1]

a    0.832793
b    0.475595
c    0.978588
d    0.735282
e    0.637385
f    0.710485
g    0.681240
h    0.736971
i    0.230949
Name: B, dtype: float64

In [264]:
selector = lambda df: df['A'] > 0

In [265]:
selector

In [266]:
df.loc[selector]

          A         B         C         D
a  0.700538  0.832793  0.744989  0.911335
b  0.172791  0.475595  0.879697  0.961754
c  0.923574  0.978588  0.064432  0.623384
d  0.265097  0.735282  0.132408  0.262589
e  0.181844  0.637385  0.549071  0.444988
f  0.526746  0.710485  0.776469  0.954320
g  0.574974  0.681240  0.086766  0.433873
h  0.435507  0.736971  0.386445  0.094802
i  0.547587  0.230949  0.284496  0.876868

In [267]:
selector = lambda df: df['A'] > 0.5

In [268]:
df.loc[selector]

          A         B         C         D
a  0.700538  0.832793  0.744989  0.911335
c  0.923574  0.978588  0.064432  0.623384
f  0.526746  0.710485  0.776469  0.954320
g  0.574974  0.681240  0.086766  0.433873
i  0.547587  0.230949  0.284496  0.876868

In [269]:
selector = lambda df: (df['A'] > 0.5)&(df['B'] < 0.2)

In [270]:
df.loc[selector]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [271]:
condition_for_selection = (df['A'] > 0.5)&(df['B'] < 0.2)

In [272]:
condition_for_selection

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
i    False
dtype: bool

In [273]:
df[condition_for_selection]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [274]:
condition_for_selection = (df['A'] > 0.5) | ~(df['B'] < 0.2)

In [275]:
df[condition_for_selection]

          A         B         C         D
a  0.700538  0.832793  0.744989  0.911335
b  0.172791  0.475595  0.879697  0.961754
c  0.923574  0.978588  0.064432  0.623384
d  0.265097  0.735282  0.132408  0.262589
e  0.181844  0.637385  0.549071  0.444988
f  0.526746  0.710485  0.776469  0.954320
g  0.574974  0.681240  0.086766  0.433873
h  0.435507  0.736971  0.386445  0.094802
i  0.547587  0.230949  0.284496  0.876868

OR operator: |
NOT operator: ~

## Adding a column in the dataframe

In [276]:
df['E'] = df['A']*100

In [277]:
df

          A         B         C         D          E
a  0.700538  0.832793  0.744989  0.911335  70.053818
b  0.172791  0.475595  0.879697  0.961754  17.279074
c  0.923574  0.978588  0.064432  0.623384  92.357385
d  0.265097  0.735282  0.132408  0.262589  26.509667
e  0.181844  0.637385  0.549071  0.444988  18.184405
f  0.526746  0.710485  0.776469  0.954320  52.674620
g  0.574974  0.681240  0.086766  0.433873  57.497427
h  0.435507  0.736971  0.386445  0.094802  43.550749
i  0.547587  0.230949  0.284496  0.876868  54.758659

In [278]:
df["F"] = df["A"] + df["C"]
# we created an extra column

In [279]:
df

          A         B         C         D          E         F
a  0.700538  0.832793  0.744989  0.911335  70.053818  1.445527
b  0.172791  0.475595  0.879697  0.961754  17.279074  1.052488
c  0.923574  0.978588  0.064432  0.623384  92.357385  0.988006
d  0.265097  0.735282  0.132408  0.262589  26.509667  0.397505
e  0.181844  0.637385  0.549071  0.444988  18.184405  0.730915
f  0.526746  0.710485  0.776469  0.954320  52.674620  1.303216
g  0.574974  0.681240  0.086766  0.433873  57.497427  0.661741
h  0.435507  0.736971  0.386445  0.094802  43.550749  0.821952
i  0.547587  0.230949  0.284496  0.876868  54.758659  0.832083

In [280]:
criteria = df['A'] < 0.4

In [281]:
criteria

a    False
b     True
c    False
d     True
e     True
f    False
g    False
h    False
i    False
Name: A, dtype: bool

In [282]:
df.loc[criteria, 'A'] = 0

In [283]:
df

          A         B         C         D          E         F
a  0.700538  0.832793  0.744989  0.911335  70.053818  1.445527
b  0.000000  0.475595  0.879697  0.961754  17.279074  1.052488
c  0.923574  0.978588  0.064432  0.623384  92.357385  0.988006
d  0.000000  0.735282  0.132408  0.262589  26.509667  0.397505
e  0.000000  0.637385  0.549071  0.444988  18.184405  0.730915
f  0.526746  0.710485  0.776469  0.954320  52.674620  1.303216
g  0.574974  0.681240  0.086766  0.433873  57.497427  0.661741
h  0.435507  0.736971  0.386445  0.094802  43.550749  0.821952
i  0.547587  0.230949  0.284496  0.876868  54.758659  0.832083

In [284]:
cities = ['Mumbai', 'Delhi', 'Chennai', 'Kolkata', 'Bengalure', 'Hyderabad', 'Pune', 'Ahmedabad', 'Indore']

In [285]:
df['city'] = cities

In [286]:
df_copy = df.copy()

In [287]:
df

          A         B         C         D          E         F       city
a  0.700538  0.832793  0.744989  0.911335  70.053818  1.445527     Mumbai
b  0.000000  0.475595  0.879697  0.961754  17.279074  1.052488      Delhi
c  0.923574  0.978588  0.064432  0.623384  92.357385  0.988006    Chennai
d  0.000000  0.735282  0.132408  0.262589  26.509667  0.397505    Kolkata
e  0.000000  0.637385  0.549071  0.444988  18.184405  0.730915  Bengalure
f  0.526746  0.710485  0.776469  0.954320  52.674620  1.303216  Hyderabad
g  0.574974  0.681240  0.086766  0.433873  57.497427  0.661741       Pune
h  0.435507  0.736971  0.386445  0.094802  43.550749  0.821952  Ahmedabad
i  0.547587  0.230949  0.284496  0.876868  54.758659  0.832083     Indore

In [288]:
cities_new = ['Mumbai', 'Delhi', 'Chennai',
              'Kolkata', 'Bengalure', 'Hyderabad',
              'Pune', 'Ahmedabad', 'Guwahati']

In [289]:
df_copy['new_city'] = cities_new

In [290]:
df_copy

,A,B,C,D,E,F,city,new_city
a,0.700538,0.832793,0.744989,0.911335,70.053818,1.445527,Mumbai,Mumbai
b,0.000000,0.475595,0.879697,0.961754,17.279074,1.052488,Delhi,Delhi
c,0.923574,0.978588,0.064432,0.623384,92.357385,0.988006,Chennai,Chennai
d,0.000000,0.735282,0.132408,0.262589,26.509667,0.397505,Kolkata,Kolkata
e,0.000000,0.637385,0.549071,0.444988,18.184405,0.730915,Bengalure,Bengalure
f,0.526746,0.710485,0.776469,0.954320,52.674620,1.303216,Hyderabad,Hyderabad
g,0.574974,0.681240,0.086766,0.433873,57.497427,0.661741,Pune,Pune
h,0.435507,0.736971,0.386445,0.094802,43.550749,0.821952,Ahmedabad,Ahmedabad
i,0.547587,0.230949,0.284496,0.876868,54.758659,0.832083,Indore,Guwahati

In [291]:
criteria = df_copy['city'].isin(['Pune', 'Bengaluru', 'Hyderabad'])

In [292]:
df_copy.loc[df.city == 'Bengalure', ['city', 'new_city']] = 'Bengaluru'

In [293]:
df_copy

,A,B,C,D,E,F,city,new_city
a,0.700538,0.832793,0.744989,0.911335,70.053818,1.445527,Mumbai,Mumbai
b,0.000000,0.475595,0.879697,0.961754,17.279074,1.052488,Delhi,Delhi
c,0.923574,0.978588,0.064432,0.623384,92.357385,0.988006,Chennai,Chennai
d,0.000000,0.735282,0.132408,0.262589,26.509667,0.397505,Kolkata,Kolkata
e,0.000000,0.637385,0.549071,0.444988,18.184405,0.730915,Bengaluru,Bengaluru
f,0.526746,0.710485,0.776469,0.954320,52.674620,1.303216,Hyderabad,Hyderabad
g,0.574974,0.681240,0.086766,0.433873,57.497427,0.661741,Pune,Pune
h,0.435507,0.736971,0.386445,0.094802,43.550749,0.821952,Ahmedabad,Ahmedabad
i,0.547587,0.230949,0.284496,0.876868,54.758659,0.832083,Indore,Guwahati

In [ ]:
?df_copy.drop

In [295]:
df_copy.drop(['new_city'], axis=1)

          A         B         C         D          E         F       city
a  0.700538  0.832793  0.744989  0.911335  70.053818  1.445527     Mumbai
b  0.000000  0.475595  0.879697  0.961754  17.279074  1.052488      Delhi
c  0.923574  0.978588  0.064432  0.623384  92.357385  0.988006    Chennai
d  0.000000  0.735282  0.132408  0.262589  26.509667  0.397505    Kolkata
e  0.000000  0.637385  0.549071  0.444988  18.184405  0.730915  Bengaluru
f  0.526746  0.710485  0.776469  0.954320  52.674620  1.303216  Hyderabad
g  0.574974  0.681240  0.086766  0.433873  57.497427  0.661741       Pune
h  0.435507  0.736971  0.386445  0.094802  43.550749  0.821952  Ahmedabad
i  0.547587  0.230949  0.284496  0.876868  54.758659  0.832083     Indore

In [296]:
criteria

a    False
b    False
c    False
d    False
e    False
f     True
g     True
h    False
i    False
Name: city, dtype: bool

In [297]:
df_copy.loc[:, 'city'] = 'Chennai'

In [ ]:
df_copy = df_copy.drop(['new_cities'], axis=1)

In [ ]:
df_copy

,A,B,C,D,E,F,city,new_city
a,0.511163,0.077225,0.712719,0.70322,51.116259,1.223882,Chennai,Mumbai
b,0.0,0.319507,0.059459,0.076181,14.465201,0.204111,Chennai,Delhi
c,0.668516,0.924316,0.190403,0.144573,66.851581,0.858919,Chennai,Chennai
d,0.470595,0.358167,0.526109,0.548248,47.059507,0.996704,Chennai,Kolkata
e,0.840948,0.981394,0.959002,0.870479,84.094789,1.79995,Chennai,Bengaluru
f,0.227027,0.259232,0.62781,0.249644,22.702716,0.854837,Chennai,Hyderabad
g,0.802435,0.969513,0.604462,0.87105,80.243516,1.406897,Chennai,Pune
h,0.660405,0.788978,0.023313,0.524337,66.040476,0.683717,Chennai,Ahmedabad
i,0.551329,0.121502,0.321013,0.481932,55.132923,0.872342,Chennai,Guwahati
city,Chennai,Chennai,Chennai,Chennai,Chennai,Chennai,Chennai,Chennai

In [ ]:
df_copy = df_copy.drop(['city'])

In [ ]:
df_copy

,A,B,C,D,E,F,city,new_city
a,0.511163,0.077225,0.712719,0.70322,51.116259,1.223882,Chennai,Mumbai
b,0.0,0.319507,0.059459,0.076181,14.465201,0.204111,Chennai,Delhi
c,0.668516,0.924316,0.190403,0.144573,66.851581,0.858919,Chennai,Chennai
d,0.470595,0.358167,0.526109,0.548248,47.059507,0.996704,Chennai,Kolkata
e,0.840948,0.981394,0.959002,0.870479,84.094789,1.79995,Chennai,Bengaluru
f,0.227027,0.259232,0.62781,0.249644,22.702716,0.854837,Chennai,Hyderabad
g,0.802435,0.969513,0.604462,0.87105,80.243516,1.406897,Chennai,Pune
h,0.660405,0.788978,0.023313,0.524337,66.040476,0.683717,Chennai,Ahmedabad
i,0.551329,0.121502,0.321013,0.481932,55.132923,0.872342,Chennai,Guwahati

In [ ]:
?df_copy.sample

In [ ]:
df_copy.sample(3)

,A,B,C,D,E,F,city,new_city
a,0.511163,0.077225,0.712719,0.70322,51.116259,1.223882,Chennai,Mumbai
g,0.802435,0.969513,0.604462,0.87105,80.243516,1.406897,Chennai,Pune
h,0.660405,0.788978,0.023313,0.524337,66.040476,0.683717,Chennai,Ahmedabad

In [ ]:
df_copy.sample(3)

,A,B,C,D,E,F,city,new_city
g,0.802435,0.969513,0.604462,0.87105,80.243516,1.406897,Chennai,Pune
a,0.511163,0.077225,0.712719,0.70322,51.116259,1.223882,Chennai,Mumbai
f,0.227027,0.259232,0.62781,0.249644,22.702716,0.854837,Chennai,Hyderabad

In [ ]:
df_copy.sample(3, random_state=42)

,A,B,C,D,E,F,city,new_city
h,0.660405,0.788978,0.023313,0.524337,66.040476,0.683717,Chennai,Ahmedabad
b,0.0,0.319507,0.059459,0.076181,14.465201,0.204111,Chennai,Delhi
f,0.227027,0.259232,0.62781,0.249644,22.702716,0.854837,Chennai,Hyderabad

In [ ]:
df_copy.sample(3, random_state=42)

,A,B,C,D,E,F,city,new_city
h,0.660405,0.788978,0.023313,0.524337,66.040476,0.683717,Chennai,Ahmedabad
b,0.0,0.319507,0.059459,0.076181,14.465201,0.204111,Chennai,Delhi
f,0.227027,0.259232,0.62781,0.249644,22.702716,0.854837,Chennai,Hyderabad

In [ ]:
df_copy.sample(3, random_state=42, replace=True)

,A,B,C,D,E,F,city,new_city
g,0.802435,0.969513,0.604462,0.87105,80.243516,1.406897,Chennai,Pune
d,0.470595,0.358167,0.526109,0.548248,47.059507,0.996704,Chennai,Kolkata
h,0.660405,0.788978,0.023313,0.524337,66.040476,0.683717,Chennai,Ahmedabad

In [298]:
import pandas as pd

cities = ['Mumbai', 'Chennai', 'Pune', 'Ahmedabad', 'Kolkata', 'Kanpur', 'Delhi']
city_df = pd.DataFrame(cities)

In [299]:
city_df.columns = ['City_Name']

In [300]:
city_df

   City_Name
0     Mumbai
1    Chennai
2       Pune
3  Ahmedabad
4    Kolkata
5     Kanpur
6      Delhi

In [301]:
condition_met = city_df.City_Name == 'Mumbai'

In [302]:
type(condition_met)

pandas.core.series.Series

In [303]:
city_df[condition_met]

  City_Name
0    Mumbai

In [304]:
condition_met

0     True
1    False
2    False
3    False
4    False
5    False
6    False
Name: City_Name, dtype: bool

In [305]:
city_df[city_df.City_Name == 'Pune']

  City_Name
2      Pune

Pandas [cheatsheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

# Agggregation and grouping

In [306]:
import numpy as np

In [307]:
random_state = np.random.RandomState(100)
random_series = pd.Series(random_state.rand(10))

In [308]:
random_series

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
7    0.825853
8    0.136707
9    0.575093
dtype: float64

Now that the series is created, we can try aggregation functions like `mean`, `std` etc.

In [309]:
random_series.mean()

0.4425757785871915

In [310]:
random_series.std()

0.2988992029497061

In [311]:
random_series.sum()

4.425757785871915

Let's create a dataframe with 5 rows and 2 columns containing random numbers.

In [312]:
df = pd.DataFrame({'A': random_state.rand(5),
                   'B': random_state.rand(5)})
df

          A         B
0  0.891322  0.978624
1  0.209202  0.811683
2  0.185328  0.171941
3  0.108377  0.816225
4  0.219697  0.274074

In [313]:
df.sum()

A    1.613927
B    3.052546
dtype: float64

In [314]:
df.mean()

A    0.322785
B    0.610509
dtype: float64

Try these operations row-wise

In [315]:
df.mean(axis=1)

0    0.934973
1    0.510443
2    0.178635
3    0.462301
4    0.246886
dtype: float64

In [316]:
df.sum(axis=1)

0    1.869946
1    1.020885
2    0.357269
3    0.924602
4    0.493771
dtype: float64

## Groupby

Three stages
* Split - we split dataframe into multiple smaller dataframe based on the values of keys
* Apply - we apply desired aggregation/transformation on each dataframe.
* Combine - we combine results from apply state into a dataframe

![split-apply-combine.png]()

In [317]:
list("ABCABC")

['A', 'B', 'C', 'A', 'B', 'C']

In [318]:
df = pd.DataFrame({'key': ['A','B','C']*2, #list("ABCABC"), ['A','B','C','A','B','C']
                   'data': range(6)})

In [319]:
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [321]:
df.groupby("key")

In [322]:
df.groupby("key").sum()

     data
key
A       3
B       5
C       7

# GRADED ASSIGNMENT - 1.1

In [323]:
import pandas as pd

In [324]:
df = pd.read_csv("V5.csv")
df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [325]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  object
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   object
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  object
 6   Residential        10000 non-null  object
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  object
dtypes: float64(4), int64(3), object(5)
memory usage: 937.6+ KB

In [328]:
df.isnull()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,True,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False

In [329]:
df.isnull().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property                0
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [330]:
1254+1243+1229

3726

In [331]:
df.shape

(10000, 12)

In [333]:
df.iloc[692,0]

'2009-11-16'

In [334]:
df.iloc[546,7]

3

In [335]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [338]:
df['Locality'].unique()

array(['Waterbury', 'Bridgeport', 'Greenwich', 'Norwalk', nan,
       'Fairfield', 'West Hartford', 'Stamford'], dtype=object)

In [340]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  object
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   object
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  object
 6   Residential        10000 non-null  object
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  object
dtypes: float64(4), int64(3), object(5)
memory usage: 937.6+ KB

In [344]:
df['Face'].isnull().sum()

0

In [347]:
df = df.dropna(thresh=10)

In [348]:
df.shape

(9978, 12)

In [349]:
df = pd.read_csv("V5.csv")

In [350]:
df = df.dropna()

In [351]:
df.shape

(6700, 12)

# Graded assignment - 1.2

In [352]:
df = pd.read_csv("V5.csv")

In [354]:
df.shape

(10000, 12)

In [355]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [356]:
df = df[::2]
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
6,2009-01-02,2009,Norwalk,571060.0,1000000.0,Single Family,Detached House,3,2,NaN,1.025953,South
8,2009-01-02,2009,NaN,603540.0,1680000.0,Single Family,Detached House,3,1,1039.0,1.025953,East

In [357]:
df.iloc[0,3]

111440.0

In [358]:
df.iloc[332,3]

256200.0

In [359]:
df = pd.read_csv("V5.csv")
df.shape

(10000, 12)

In [360]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [361]:
df = df[1::2]
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
7,2009-01-02,2009,Greenwich,592760.0,920000.0,Single Family,Detached House,3,3,937.0,1.025953,North
9,2009-01-02,2009,Bridgeport,137901.0,245000.0,Single Family,Detached House,3,1,956.0,1.025953,West

In [363]:
df.iloc[332,3]

352940.0

In [364]:
df = pd.read_csv("V5.csv")
df.shape

(10000, 12)

In [368]:
df_c_o = df.iloc[:,1::2]
df_c_o.head()

   Year  Estimated Value       Property  num_rooms  carpet_area   Face
0  2009         111440.0  Single Family          3        996.0  South
1  2009         124670.0     Two Family          4       1241.0  South
2  2009          55720.0  Single Family          3        910.0  South
3  2009        4775276.0  Single Family          3        971.0   East
4  2009         112351.0              ?          3       1092.0   East

In [370]:
df_c_o.iloc[100,5]

'West'

In [371]:
df_e = df.iloc[::2,::2]
df_e.head()

,Date,Locality,Sale Price,Residential,num_bathrooms,property_tax_rate
0,2009-01-02,Waterbury,185000.0,Detached House,3,1.025953
2,2009-01-02,Waterbury,140000.0,Detached House,2,1.025953
4,2009-01-02,Bridgeport,210000.0,Detached House,2,1.025953
6,2009-01-02,Norwalk,1000000.0,Detached House,2,1.025953
8,2009-01-02,NaN,1680000.0,Detached House,1,1.025953

In [373]:
df_e.iloc[255,3]

'Detached House'

In [374]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [381]:
df['Year'].value_counts(ascending = True)

Year
2010    532
2011    539
2013    578
2014    630
2018    641
2015    699
2012    708
2020    724
2009    766
2022    789
2016    799
2019    800
2017    866
2021    929
Name: count, dtype: int64

In [384]:
criteria = (df['Year']==2017) | (df['Year'] == 2021) | (df['Year']==2019) | (df['Year'] == 2016) | (df['Year']==2022)

In [385]:
df[criteria].shape

(4183, 12)

In [386]:
criteria = (df['num_rooms']==3) & (df['num_bathrooms']==3)

In [387]:
df[criteria].shape

(2730, 12)

In [389]:
criteria = (df['num_rooms']==3) | (df['num_bathrooms']==3)

In [390]:
df[criteria].shape

(8591, 12)

In [393]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [396]:
df.tail()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [397]:
df['Date'][5:6]

5    2009-01-02
Name: Date, dtype: object

In [394]:
criteria = (df['Locality']=="Greenwich") & (df['Year']==2022) & (df['num_rooms']==3) & ((df['Face']=="North") | (df['Face']=="East"))

In [395]:
df[criteria].shape

(42, 12)

In [433]:
df['month'] = df["Date"].str[5:7]

In [434]:
df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face,month
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South,01
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South,01
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South,01
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East,01
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North,09
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North,09
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South,09
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North,09
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East,09

In [439]:
criteria = (df['month'] == "08")

In [440]:
df[criteria].shape

(1050, 13)

In [449]:
df.shape

(10000, 13)

In [448]:
df.groupby("Locality").sum()

,Date,Year,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face,month
Locality,,,,,,,,,,,,
Bridgeport,2009-01-022009-01-022009-01-022009-01-022009-0...,3539487,2.686580e+08,3.057114e+08,Two FamilySingle Family?Single FamilySingle Fa...,DuplexDetached HouseDetached HouseDetached Hou...,6618,4803,1950321.0,1978.067605,SouthEastEastWestSouthEastSouthNorthEastWestWe...,0101010101010101010101010101010101010101010101...
Fairfield,2009-01-052009-01-122009-01-192009-01-262009-0...,2409116,5.474476e+08,8.696284e+08,Single FamilySingle FamilySingle FamilySingle ...,Detached HouseDetached HouseDetached HouseDeta...,3612,2419,1048854.0,1359.622824,SouthEastEastWestSouthWestSouthNorthNorthNorth...,0101010101010202020202020303030303030303030404...
Greenwich,2009-01-022009-01-022009-01-032009-01-052009-0...,2116662,1.426266e+09,2.383735e+09,Single FamilySingle FamilySingle FamilySingle ...,Detached HouseDetached HouseDetached HouseDeta...,3245,2173,938725.0,1207.559718,NorthNorthSouthNorthWestNorthEastSouthEastEast...,0101010101010101010202020202020303030303030303...
Norwalk,2009-01-022009-01-032009-01-042009-01-082009-0...,1971334,3.192768e+08,5.467958e+08,Single FamilySingle FamilySingle Family?Single...,Detached HouseDetached HouseDetached HouseDeta...,3070,2121,898459.0,1139.923284,SouthNorthSouthSouthSouthNorthWestNorthWestEas...,0101010101010101010101020202020202020303030303...
Stamford,2010-10-022010-10-142010-10-162010-10-172010-1...,2139698,4.336563e+08,6.689937e+08,?Single Family?Single FamilySingle Family?Sing...,Detached HouseDetached HouseDetached HouseDeta...,3373,2290,978466.0,1246.875296,EastWestWestSouthNorthWestSouthEastSouthWestEa...,1010101010101111111111111212121212010101010202...
Waterbury,2009-01-022009-01-022009-01-052009-01-052009-0...,3102061,1.280942e+08,1.634651e+08,Single FamilySingle FamilySingle FamilyThree F...,Detached HouseDetached HouseDetached HouseTrip...,5619,4058,1649988.0,1773.656088,SouthSouthSouthNorthWestSouthWestNorthWestSout...,0101010101010101010101010101020202020202020202...
West Hartford,2009-10-012009-10-012009-10-022009-10-092009-1...,2354833,2.350785e+08,3.954231e+08,Single FamilySingle FamilySingle Family?Single...,Detached HouseDetached HouseDetached HouseDeta...,3615,2430,1061530.0,1339.657805,SouthEastWestWestSouthEastEastEastEastEastEast...,1010101010101010101111111111111111111212121212...